language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - flake8 src
  - rs -n "res/networks/triangle.graphml" -sf "res/service_functions/abc.yaml" -c "res/config/sim_config.yaml" -i 50
